<a href="https://colab.research.google.com/github/sudharshanpaul/Machine-Learning/blob/main/EDA/Feature_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature Encoding

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [ ]:
df = pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
df.head(5)

   RowNumber  CustomerId   Surname  CreditScore  ... HasCrCard IsActiveMember  EstimatedSalary  Exited
0          1    15634602  Hargrave          619  ...         1              1        101348.88       1
1          2    15647311      Hill          608  ...         0              1        112542.58       0
2          3    15619304      Onio          502  ...         1              0        113931.57       1
3          4    15701354      Boni          699  ...         0              0         93826.63       0
4          5    15737888  Mitchell          850  ...         1              1         79084.10       0

[5 rows x 14 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           9884 non-null   object
 6   Age              9864 non-null   float64
 7   Tenure           9999 non-null   float64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(4), int64(7), object(3)
memory usage: 1.1+ MB

In [ ]:
df.drop(columns=['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

Let's do Encoding for the Gender column

#####Handling Missing Values

In [ ]:
df.Gender.value_counts()

Gender
Male      5506
Female    4494
Name: count, dtype: int64

In [ ]:
df.Gender.mode()[0]

'Male'

In [ ]:
df.Gender = df.Gender.fillna(df.Gender.mode()[0])

In [ ]:
df.Gender.value_counts()

Gender
Male      5506
Female    4494
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              9864 non-null   float64
 4   Tenure           9999 non-null   float64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
 11  Gender_label     10000 non-null  int64
dtypes: float64(4), int64(6), object(2)
memory usage: 937.6+ KB

## Label Encoding

In [ ]:
le = preprocessing.LabelEncoder()
df['Gender_label'] = le.fit_transform(df.Gender)
df.head(5)

   CreditScore Geography  Gender   Age  ...  IsActiveMember  EstimatedSalary  Exited  Gender_label
0          619    France  Female   NaN  ...               1        101348.88       1             0
1          608     Spain  Female  41.0  ...               1        112542.58       0             0
2          502    France  Female  42.0  ...               0        113931.57       1             0
3          699    France  Female  39.0  ...               0         93826.63       0             0
4          850     Spain    Male   NaN  ...               1         79084.10       0             1

[5 rows x 12 columns]

In [ ]:
df.Gender_label.value_counts()

Gender_label
1    5506
0    4494
Name: count, dtype: int64

In [ ]:
df['Geography_label'] = le.fit_transform(df.Geography)
df.head(5)

   CreditScore Geography  Gender   Age  ...  EstimatedSalary  Exited  Gender_label  Geography_label
0          619    France  Female   NaN  ...        101348.88       1             0                0
1          608     Spain  Female  41.0  ...        112542.58       0             0                2
2          502    France  Female  42.0  ...        113931.57       1             0                0
3          699    France  Female  39.0  ...         93826.63       0             0                0
4          850     Spain    Male   NaN  ...         79084.10       0             1                2

[5 rows x 13 columns]

In [ ]:
df.Geography_label.value_counts()

Geography_label
0    5014
1    2509
2    2477
Name: count, dtype: int64

In [ ]:
df.drop(columns=['Geography_label'],axis=1,inplace=True)

In [ ]:
df.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited', 'Gender_label'],
      dtype='object')

## One Hot Encoding

In [ ]:
help(pd.get_dummies)

Help on function get_dummies in module pandas.core.reshape.encoding:

get_dummies(data, prefix=None, prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_', dummy_na: 'bool' = False, columns=None, sparse: 'bool' = False, drop_first: 'bool' = False, dtype: 'NpDtype | None' = None) -> 'DataFrame'
    Convert categorical variable into dummy/indicator variables.

    Each variable is converted in as many 0/1 variables as there are different
    values. Columns in the output are each named after a value; if the input is
    a DataFrame, the name of the original variable is prepended to the value.

    Parameters
    ----------
    data : array-like, Series, or DataFrame
        Data of which to get dummy indicators.
    prefix : str, list of str, or dict of str, default None
        String to append DataFrame column names.
        Pass a list with length equal to the number of columns
        when calling get_dummies on a DataFrame. Alternatively, `prefix`
        can be a dictionary mapping column names to prefixes.
    prefix_sep : str, default '_'
        If appending prefix, separator/delimiter to use. Or pass a
        list or dictionary as with `prefix`.
    dummy_na : bool, default False
        Add a column to indicate NaNs, if False NaNs are ignored.
    columns : list-like, default None
        Column names in the DataFrame to be encoded.
        If `columns` is None then all the columns with
        `object`, `string`, or `category` dtype will be converted.
    sparse : bool, default False
        Whether the dummy-encoded columns should be backed by
        a :class:`SparseArray` (True) or a regular NumPy array (False).
    drop_first : bool, default False
        Whether to get k-1 dummies out of k categorical levels by removing the
        first level.
    dtype : dtype, default bool
        Data type for new columns. Only a single dtype is allowed.

    Returns
    -------
    DataFrame
        Dummy-coded data. If `data` contains other columns than the
        dummy-coded one(s), these will be prepended, unaltered, to the result.

    See Also
    --------
    Series.str.get_dummies : Convert Series of strings to dummy codes.
    :func:`~pandas.from_dummies` : Convert dummy codes to categorical ``DataFrame``.

    Notes
    -----
    Reference :ref:`the user guide <reshaping.dummies>` for more examples.

    Examples
    --------
    >>> s = pd.Series(list('abca'))

    >>> pd.get_dummies(s)
           a      b      c
    0   True  False  False
    1  False   True  False
    2  False  False   True
    3   True  False  False

    >>> s1 = ['a', 'b', np.nan]

    >>> pd.get_dummies(s1)
           a      b
    0   True  False
    1  False   True
    2  False  False

    >>> pd.get_dummies(s1, dummy_na=True)
           a      b    NaN
    0   True  False  False
    1  False   True  False
    2  False  False   True

    >>> df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
    ...                    'C': [1, 2, 3]})

    >>> pd.get_dummies(df, prefix=['col1', 'col2'])
       C  col1_a  col1_b  col2_a  col2_b  col2_c
    0  1    True   False   False    True   False
    1  2   False    True    True   False   False
    2  3    True   False   False   False    True

    >>> pd.get_dummies(pd.Series(list('abcaa')))
           a      b      c
    0   True  False  False
    1  False   True  False
    2  False  False   True
    3   True  False  False
    4   True  False  False

    >>> pd.get_dummies(pd.Series(list('abcaa')), drop_first=True)
           b      c
    0  False  False
    1   True  False
    2  False   True
    3  False  False
    4  False  False

    >>> pd.get_dummies(pd.Series(list('abc')), dtype=float)
         a    b    c
    0  1.0  0.0  0.0
    1  0.0  1.0  0.0
    2  0.0  0.0  1.0

In [ ]:
one_hot = pd.get_dummies(df.Geography,dtype=int)

In [ ]:
one_hot.head(5)

   France  Germany  Spain
0       1        0      0
1       0        0      1
2       1        0      0
3       1        0      0
4       0        0      1

In [ ]:
df.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited', 'Gender_label'],
      dtype='object')

In [ ]:
df_dummies = pd.get_dummies(df,dtype=int)
df_dummies.head(5)

   CreditScore   Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0          619   NaN     2.0  ...                0              1            0
1          608  41.0     1.0  ...                1              1            0
2          502  42.0     8.0  ...                0              1            0
3          699  39.0     1.0  ...                0              1            0
4          850   NaN     2.0  ...                1              0            1

[5 rows x 15 columns]

## Dummy Encoding

In [ ]:
df_dummies_de = pd.get_dummies(df,drop_first=True,dtype=int)

df_dummies_de.head(5)

   CreditScore   Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   NaN     2.0  ...                  0                0            0
1          608  41.0     1.0  ...                  0                1            0
2          502  42.0     8.0  ...                  0                0            0
3          699  39.0     1.0  ...                  0                0            0
4          850   NaN     2.0  ...                  0                1            1

[5 rows x 13 columns]

## Target Encoding

In [ ]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.4-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.13.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.4)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.1)
Downloading category_encoders-2.6.4-py2.py3-none-any.whl (82 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.0/82.0 kB 7.3 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.4

In [ ]:
from category_encoders import TargetEncoder

In [ ]:
t_encoder = TargetEncoder()
df1 = pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
df1.drop(columns=['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [ ]:
df1['Gender'] = df1.Gender.fillna(df1.Gender.mode()[0])

In [ ]:
df1['Gender Encoded'] = t_encoder.fit_transform(df1.Gender,df1.Exited)
df1.head(5)

   CreditScore Geography  Gender   Age  ...  IsActiveMember  EstimatedSalary  Exited  Gender Encoded
0          619    France  Female   NaN  ...               1        101348.88       1        0.250334
1          608     Spain  Female  41.0  ...               1        112542.58       0        0.250334
2          502    France  Female  42.0  ...               0        113931.57       1        0.250334
3          699    France  Female  39.0  ...               0         93826.63       0        0.250334
4          850     Spain    Male   NaN  ...               1         79084.10       0        0.165637

[5 rows x 12 columns]

Now we can use this Gender Encoded feature instead of Gender and this is only done when there is target variable

In [ ]:
df1['Gender Encoded'].value_counts()

Gender Encoded
0.165637    5506
0.250334    4494
Name: count, dtype: int64

***Benifits of Target Encoding***
- Target encoding is a simple and quick encoding method that doesn't add to the dimensionality of the dataset
Therefore, it may be used as a good first try technique

***Limitations***
- It is dependent on the target distributionn which means target encoding requires careful validation as it can be prone to overfitting.

In [ ]:
from category_encoders import HashingEncoder

In [ ]:
X = df.Gender

In [ ]:
y = df.Exited

In [ ]:
ce_hash = HashingEncoder(cols=['Gender'])
ce_hash.fit_transform(X,y)

ValueError: X does not contain the columns listed in cols

In [ ]:
X = df.Geography

In [ ]:
ce_hash2 = HashingEncoder(cols=['Geography'])
ce_hash2.fit_transform(X,y)

      col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7
0         0      1      0      0      0      0      0      0
1         0      0      0      1      0      0      0      0
2         0      1      0      0      0      0      0      0
3         0      1      0      0      0      0      0      0
4         0      0      0      1      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...    ...
9995      0      1      0      0      0      0      0      0
9996      0      1      0      0      0      0      0      0
9997      0      1      0      0      0      0      0      0
9998      0      0      0      0      0      0      0      1
9999      0      1      0      0      0      0      0      0

[10000 rows x 8 columns]

In [ ]:
ce_hash2 = HashingEncoder(n_components=16,cols=['Geography'])
ce_hash2.fit_transform(X,y)

      col_0  col_1  col_2  col_3  col_4  col_5  ...  col_10  col_11  col_12  col_13  col_14  col_15
0         0      1      0      0      0      0  ...       0       0       0       0       0       0
1         0      0      0      0      0      0  ...       0       1       0       0       0       0
2         0      1      0      0      0      0  ...       0       0       0       0       0       0
3         0      1      0      0      0      0  ...       0       0       0       0       0       0
4         0      0      0      0      0      0  ...       0       1       0       0       0       0
...     ...    ...    ...    ...    ...    ...  ...     ...     ...     ...     ...     ...     ...
9995      0      1      0      0      0      0  ...       0       0       0       0       0       0
9996      0      1      0      0      0      0  ...       0       0       0       0       0       0
9997      0      1      0      0      0      0  ...       0       0       0       0       0       0
9998      0      0      0      0      0      0  ...       0       0       0       0       0       1
9999      0      1      0      0      0      0  ...       0       0       0       0       0       0

[10000 rows x 16 columns]